name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
        tar -zxvf allure-2.24.1.tgz
        sudo mv allure-2.24.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        echo "/opt/allure/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make requirement

    - name: Lint with flake8
      run: |
        make flake8

    - name: Test with pytest
      run: |
        make run-test

    - name: Generate Allure report
      run: |
        allure generate --single-file --clean allure-results -o allure-report

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: allure-report/index.html
        if-no-files-found: warn