name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version

    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make requirement

    - name: Lint with flake8
      run: |
        make flake8

    - name: Test with pytest
      run: |
        make run-test

    - name: Generate Allure report
      run: |
        allure generate --single-file --clean allure-results -o allure-report

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: allure-report/index.html
        if-no-files-found: warn